[package]
name = "lec3"
version = "1.0.0"
authors = []

[addresses]
MyAddr ='42f828c3c64cddf473db97f807e39a7faa3684260a952a97807ac44bcf250c37'
Std = "0x1"
aptos_std = "0x1"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
