[package]
name = "task"
version = "1.0.0"
authors = []

[addresses]
MyAddr ='0xaeb489f1b55ebb7b00926879ea2dceaf7bac94556649b83e1dd1a2bf41c017c8'
Std = "0x1"
aptos_std = "0x1"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
